/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication;

import java.awt.Color;
import java.awt.Container;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author niraj
 */
public class Leadership extends javax.swing.JFrame {

    /**
     * Creates new form Leadership
     */
    public Leadership() {
        Container c = getContentPane();
        c.setBackground(new Color(0,153,204));
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        l1 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        l4 = new javax.swing.JLabel();
        l5 = new javax.swing.JLabel();
        l6 = new javax.swing.JLabel();
        l7 = new javax.swing.JLabel();
        l8 = new javax.swing.JLabel();
        l9 = new javax.swing.JLabel();
        l10 = new javax.swing.JLabel();
        l11 = new javax.swing.JLabel();
        l12 = new javax.swing.JLabel();
        l13 = new javax.swing.JLabel();
        l14 = new javax.swing.JLabel();
        l15 = new javax.swing.JLabel();
        l16 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(59, 144, 246));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("URW Palladio L", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(247, 248, 248));
        jLabel1.setText("Leadership");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 12, -1, -1));

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 243, 243));
        jLabel2.setText("Events");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 92, -1, -1));

        jLabel3.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(241, 247, 248));
        jLabel3.setText("+ Post Events");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 92, -1, -1));

        jLabel4.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(247, 249, 250));
        jLabel4.setText("<<<");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        l1.setForeground(new java.awt.Color(243, 250, 252));
        jPanel1.add(l1, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 131, -1, -1));

        l2.setForeground(new java.awt.Color(239, 245, 247));
        jPanel1.add(l2, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 155, -1, -1));

        l3.setForeground(new java.awt.Color(240, 244, 245));
        jPanel1.add(l3, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 179, -1, -1));

        l4.setForeground(new java.awt.Color(237, 243, 245));
        jPanel1.add(l4, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 203, -1, -1));

        l5.setForeground(new java.awt.Color(244, 247, 248));
        jPanel1.add(l5, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 284, -1, -1));

        l6.setForeground(new java.awt.Color(236, 244, 247));
        jPanel1.add(l6, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 308, -1, -1));

        l7.setForeground(new java.awt.Color(241, 247, 248));
        jPanel1.add(l7, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 332, -1, -1));

        l8.setForeground(new java.awt.Color(241, 248, 250));
        jPanel1.add(l8, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 356, -1, -1));

        l9.setForeground(new java.awt.Color(236, 244, 247));
        jPanel1.add(l9, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 131, -1, -1));

        l10.setForeground(new java.awt.Color(244, 249, 250));
        jPanel1.add(l10, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 155, -1, -1));

        l11.setForeground(new java.awt.Color(240, 249, 252));
        jPanel1.add(l11, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 179, -1, -1));

        l12.setForeground(new java.awt.Color(236, 244, 247));
        jPanel1.add(l12, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 203, -1, -1));

        l13.setForeground(new java.awt.Color(247, 249, 250));
        jPanel1.add(l13, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 284, -1, -1));

        l14.setForeground(new java.awt.Color(237, 243, 245));
        jPanel1.add(l14, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 308, -1, -1));

        l15.setForeground(new java.awt.Color(237, 243, 245));
        jPanel1.add(l15, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 332, -1, -1));

        l16.setForeground(new java.awt.Color(238, 247, 250));
        jPanel1.add(l16, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 356, -1, -1));

        jLabel14.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(244, 249, 250));
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 131, 15, -1));

        jButton1.setText("Book");
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 233, -1, -1));

        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 233, -1, -1));

        jButton3.setText("Book");
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 386, -1, -1));

        jButton4.setText("Delete");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 386, -1, -1));

        jButton5.setText("Book");
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 233, -1, -1));

        jButton6.setText("Delete");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(522, 233, -1, -1));

        jButton7.setText("Book");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 386, -1, -1));

        jButton8.setText("Delete");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(534, 386, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 33, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 634, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 23, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        HomePage hp = new HomePage();
        this.hide();
        hp.setVisible(true);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        LeadershipPost pe = new LeadershipPost();
        this.hide();
        pe.setVisible(true);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        Connection con;
        PreparedStatement pst;
        ResultSet rs;
        try {
            String L1,L2,L3,L4,L5,L6,L7,L8,L9,L10,L11,L12,L13,L14,L15,L16;
            L1 = l1.getText();
            L2 = l2.getText();
            L3 = l3.getText();
            L4 = l4.getText();
            L5 = l5.getText();
            L6 = l6.getText();
            L7 = l7.getText();
            L8 = l8.getText();
            L9 = l9.getText();
            L10 = l10.getText();
            L11 = l11.getText();
            L12 = l12.getText();
            L13 = l13.getText();
            L14 = l14.getText();
            L15 = l15.getText();
            L16 = l16.getText();
                   
            
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/javaProject","root","");
            String sql = "select * from Leadership where id=1";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();

            while(rs.next()){
            String a = rs.getString("EventName");
            l1.setText(a);
            String b = rs.getString("EventTime");
            l2.setText(b);
            String c = rs.getString("EventDate");
            l3.setText(c);
            String d = rs.getString("EventVenue");
            l4.setText(d);
            
            String sql1 = "select * from Leadership where id=2";
            pst = con.prepareStatement(sql1);
            rs = pst.executeQuery();
            while(rs.next()){
            String e = rs.getString("EventName");
            l5.setText(e);
            String f = rs.getString("EventTime");
            l6.setText(f);
            String g = rs.getString("EventDate");
            l7.setText(g);
            String h = rs.getString("EventVenue");
            l8.setText(h);
            }
            String sql2 = "select * from Leadership where id=3";
            pst = con.prepareStatement(sql2);
            rs = pst.executeQuery();
            while(rs.next()){
            String e = rs.getString("EventName");
            l9.setText(e);
            String f = rs.getString("EventTime");
            l10.setText(f);
            String g = rs.getString("EventDate");
            l11.setText(g);
            String h = rs.getString("EventVenue");
            l12.setText(h);
            }
            String sql3 = "select * from Leadership where id=4";
            pst = con.prepareStatement(sql3);
            rs = pst.executeQuery();
            while(rs.next()){
            String e = rs.getString("EventName");
            l13.setText(e);
            String f = rs.getString("EventTime");
            l14.setText(f);
            String g = rs.getString("EventDate");
            l15.setText(g);
            String h = rs.getString("EventVenue");
            l16.setText(h);
            }

            }
        
        }
        catch (Exception e){
        JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        // TODO add your handling code here:
        Connection con;
        PreparedStatement pst;
        int yesNo = JOptionPane.showConfirmDialog(null, "Delete this Post?","Delete",JOptionPane.YES_NO_OPTION);
        if(yesNo == JOptionPane.YES_OPTION){
  
            try {
                
                Class.forName("com.mysql.cj.jdbc.Driver");
                con = DriverManager.getConnection("jdbc:mysql://localhost/javaProject","root","");
                String  query1 = "delete from Leadership where id=3";
                pst = con.prepareStatement(query1);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(this, "Deleted Successfully!");
                System.out.print("is successfully deleted.");
                
              
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Entertainment.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(Entertainment.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        // TODO add your handling code here:
        Connection con;
        PreparedStatement pst;
        int yesNo = JOptionPane.showConfirmDialog(null, "Delete this Post?","Delete",JOptionPane.YES_NO_OPTION);
        if(yesNo == JOptionPane.YES_OPTION){
  
            try {
                
                Class.forName("com.mysql.cj.jdbc.Driver");
                con = DriverManager.getConnection("jdbc:mysql://localhost/javaProject","root","");
                String  query1 = "delete from Leadership where id=4";
                pst = con.prepareStatement(query1);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(this, "Deleted Successfully!");
                System.out.print("is successfully deleted.");
                
              
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Entertainment.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(Entertainment.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
    }//GEN-LAST:event_jPanel1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Connection con;
        PreparedStatement pst;
        int yesNo = JOptionPane.showConfirmDialog(null, "Delete this Post?","Delete",JOptionPane.YES_NO_OPTION);
        if(yesNo == JOptionPane.YES_OPTION){
  
            try {
                
                Class.forName("com.mysql.cj.jdbc.Driver");
                con = DriverManager.getConnection("jdbc:mysql://localhost/javaProject","root","");
                String  query1 = "delete from Leadership where id=1";
                pst = con.prepareStatement(query1);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(this, "Deleted Successfully!");
                System.out.print("is successfully deleted.");
                
              
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Entertainment.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(Entertainment.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Connection con;
        PreparedStatement pst;
        int yesNo = JOptionPane.showConfirmDialog(null, "Delete this Post?","Delete",JOptionPane.YES_NO_OPTION);
        if(yesNo == JOptionPane.YES_OPTION){
  
            try {
                
                Class.forName("com.mysql.cj.jdbc.Driver");
                con = DriverManager.getConnection("jdbc:mysql://localhost/javaProject","root","");
                String  query1 = "delete from Leadership where id=2";
                pst = con.prepareStatement(query1);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(this, "Deleted Successfully!");
                System.out.print("is successfully deleted.");
                
              
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Entertainment.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(Entertainment.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        Connection con;
        PreparedStatement pst;
        int yesNo = JOptionPane.showConfirmDialog(null, "Delete this Post?","Delete",JOptionPane.YES_NO_OPTION);
        if(yesNo == JOptionPane.YES_OPTION){
  
            try {
                
                Class.forName("com.mysql.cj.jdbc.Driver");
                con = DriverManager.getConnection("jdbc:mysql://localhost/javaProject","root","");
                String  query1 = "delete from Leadership where id=3";
                pst = con.prepareStatement(query1);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(this, "Deleted Successfully!");
                System.out.print("is successfully deleted.");
                
              
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Entertainment.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(Entertainment.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        Connection con;
        PreparedStatement pst;
        int yesNo = JOptionPane.showConfirmDialog(null, "Delete this Post?","Delete",JOptionPane.YES_NO_OPTION);
        if(yesNo == JOptionPane.YES_OPTION){
  
            try {
                
                Class.forName("com.mysql.cj.jdbc.Driver");
                con = DriverManager.getConnection("jdbc:mysql://localhost/javaProject","root","");
                String  query1 = "delete from Leadership where id=4";
                pst = con.prepareStatement(query1);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(this, "Deleted Successfully!");
                System.out.print("is successfully deleted.");
                
              
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Entertainment.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(Entertainment.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Leadership.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Leadership.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Leadership.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Leadership.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Leadership().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l10;
    private javax.swing.JLabel l11;
    private javax.swing.JLabel l12;
    private javax.swing.JLabel l13;
    private javax.swing.JLabel l14;
    private javax.swing.JLabel l15;
    private javax.swing.JLabel l16;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel l5;
    private javax.swing.JLabel l6;
    private javax.swing.JLabel l7;
    private javax.swing.JLabel l8;
    private javax.swing.JLabel l9;
    // End of variables declaration//GEN-END:variables
}
